#define DMM_SUITE_VERSION 2
#define DMM_IGNORE_AREAS (1<<0)
#define DMM_IGNORE_TURFS (1<<1)
#define DMM_IGNORE_OBJS (1<<2)
#define DMM_IGNORE_NPCS (1<<3)
#define DMM_IGNORE_PLAYERS (1<<4)
#define DMM_IGNORE_MOBS DMM_IGNORE_NPCS | DMM_IGNORE_PLAYERS
#define DMM_IGNORE_OVERLAYS (1<<5)
#define DMM_IGNORE_SPACE (1<<6)

#define DMM_OVERWRITE_MOBS 1
#define DMM_OVERWRITE_OBJS 2
