#include "..\warwip\gehenna_colony.dmm"
#include "..\z2.dmm"
#include "..\warwip\z3_gehenna.dmm"
#include "z4.dm"
#include "..\z5.dmm"
#include "nudebris.dm"
#include "..\z3.dmm"
#define MAP_MODE "standard"
