name: "Update Changelog"
on:
  push:
    branches:
      - master

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    if: github.repository == 'coolstation/coolstation'
    steps:
    - name: Get The Script
      run: |
        wget "https://raw.githubusercontent.com/${{ github.repository }}/master/.github/update_changelog.py"
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygithub pytz
    - name: Update Changelog
      run: |
        python update_changelog.py
      env:
        REPO: ${{ github.repository }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CHANGELOG_PATH: strings/changelog.txt
        ASS_CHANGELOG_PATH: strings/ass_changelog.txt
        GIT_EMAIL: "coolstation@coolstation.space"
        GIT_NAME: "coolstation"
